# Generated by Django 5.0.2 on 2025-02-21 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(unique=True, verbose_name='Serial Number / رقم التسلسل')),
                ('name_arabic', models.CharField(max_length=100, verbose_name='Arabic Name / الاسم بالعربي')),
                ('name_english', models.CharField(blank=True, max_length=100, verbose_name='English Name / الاسم بالانجليزي')),
                ('name_scientific', models.CharField(max_length=100, verbose_name='Scientific Name / الاسم العلمي')),
                ('classification', models.CharField(max_length=100, verbose_name='Classification / التصنيف')),
                ('seed_shape_arabic', models.CharField(max_length=100, verbose_name='Seed Shape (Arabic) / شكل البذرة')),
                ('seed_shape_english', models.CharField(blank=True, max_length=100, verbose_name='Seed Shape (English)')),
                ('cotyledon_type', models.CharField(choices=[('MONO', 'Monocotyledon / فلقة واحدة'), ('DI', 'Dicotyledon / فلقتين')], max_length=4, verbose_name='Cotyledon Type / نوع الفلقة')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='PlantFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_arabic', models.CharField(max_length=100, verbose_name='Arabic Name')),
                ('name_english', models.CharField(blank=True, max_length=100, verbose_name='English Name')),
                ('name_scientific', models.CharField(blank=True, max_length=100, verbose_name='Scientific Name')),
                ('description_arabic', models.TextField(blank=True, verbose_name='Arabic Description')),
                ('description_english', models.TextField(blank=True, verbose_name='English Description')),
            ],
            options={
                'verbose_name': 'Plant Family',
                'verbose_name_plural': 'Plant Families',
            },
        ),
        migrations.CreateModel(
            name='MaleFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepals', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sepals / الكأس/سبالات')),
                ('petals', models.CharField(blank=True, max_length=255, null=True, verbose_name='Petals / التويج/بتلات')),
                ('stamens', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stamens / الاسدية/الطلع')),
                ('carpels', models.CharField(blank=True, max_length=255, null=True, verbose_name='Carpels / الكربلات')),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='male_flower', to='api.plant')),
            ],
            options={
                'verbose_name': 'Male Flower',
                'verbose_name_plural': 'Male Flowers',
            },
        ),
        migrations.CreateModel(
            name='HermaphroditeFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepals', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sepals / الكأس/سبالات')),
                ('petals', models.CharField(blank=True, max_length=255, null=True, verbose_name='Petals / التويج/بتلات')),
                ('stamens', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stamens / الاسدية/الطلع')),
                ('carpels', models.CharField(blank=True, max_length=255, null=True, verbose_name='Carpels / الكربلات')),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hermaphrodite_flower', to='api.plant')),
            ],
            options={
                'verbose_name': 'Hermaphrodite Flower',
                'verbose_name_plural': 'Hermaphrodite Flowers',
            },
        ),
        migrations.CreateModel(
            name='FlowerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('UNISEXUAL', 'Unisexual / أحادية الجنس'), ('HERMAPHRODITE', 'Hermaphrodite / خنثى'), ('BOTH', 'Both Types / النوعين')], max_length=20, verbose_name='Flower Type / نوع الزهرة')),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flower_type', to='api.plant')),
            ],
        ),
        migrations.CreateModel(
            name='FemaleFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepals', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sepals / الكأس/سبالات')),
                ('petals', models.CharField(blank=True, max_length=255, null=True, verbose_name='Petals / التويج/بتلات')),
                ('stamens', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stamens / الاسدية/الطلع')),
                ('carpels', models.CharField(blank=True, max_length=255, null=True, verbose_name='Carpels / الكربلات')),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='female_flower', to='api.plant')),
            ],
            options={
                'verbose_name': 'Female Flower',
                'verbose_name_plural': 'Female Flowers',
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.plantfamily', verbose_name='Family / العائلة'),
        ),
    ]
