# Generated by Django 5.0.2 on 2025-02-23 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_plant_plantfamily_maleflower_hermaphroditeflower_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='plant',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='plant',
            name='flower_type',
            field=models.CharField(choices=[('BOTH', 'Both Male and Female / ذكرية وأنثوية'), ('HERMAPHRODITE', 'Hermaphrodite / خنثى')], default='HERMAPHRODITE', max_length=20, verbose_name='Flower Type / نوع الزهرة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='femaleflower',
            name='carpels',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Carpels / الكرابل'),
        ),
        migrations.AlterField(
            model_name='femaleflower',
            name='petals',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Petals / البتلات'),
        ),
        migrations.AlterField(
            model_name='femaleflower',
            name='plant',
            field=models.OneToOneField(limit_choices_to={'flower_type': 'BOTH'}, on_delete=django.db.models.deletion.CASCADE, related_name='female_flower', to='api.plant'),
        ),
        migrations.AlterField(
            model_name='femaleflower',
            name='sepals',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sepals / السبلات'),
        ),
        migrations.AlterField(
            model_name='femaleflower',
            name='stamens',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stamens / المتك'),
        ),
        migrations.AlterField(
            model_name='hermaphroditeflower',
            name='carpels',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Carpels / الكرابل'),
        ),
        migrations.AlterField(
            model_name='hermaphroditeflower',
            name='petals',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Petals / البتلات'),
        ),
        migrations.AlterField(
            model_name='hermaphroditeflower',
            name='plant',
            field=models.OneToOneField(limit_choices_to={'flower_type': 'HERMAPHRODITE'}, on_delete=django.db.models.deletion.CASCADE, related_name='hermaphrodite_flower', to='api.plant'),
        ),
        migrations.AlterField(
            model_name='hermaphroditeflower',
            name='sepals',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sepals / السبلات'),
        ),
        migrations.AlterField(
            model_name='hermaphroditeflower',
            name='stamens',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stamens / المتك'),
        ),
        migrations.AlterField(
            model_name='maleflower',
            name='carpels',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Carpels / الكرابل'),
        ),
        migrations.AlterField(
            model_name='maleflower',
            name='petals',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Petals / البتلات'),
        ),
        migrations.AlterField(
            model_name='maleflower',
            name='plant',
            field=models.OneToOneField(limit_choices_to={'flower_type': 'BOTH'}, on_delete=django.db.models.deletion.CASCADE, related_name='male_flower', to='api.plant'),
        ),
        migrations.AlterField(
            model_name='maleflower',
            name='sepals',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sepals / السبلات'),
        ),
        migrations.AlterField(
            model_name='maleflower',
            name='stamens',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stamens / المتك'),
        ),
        migrations.DeleteModel(
            name='FlowerType',
        ),
    ]
