# Generated by Django 5.0.2 on 2025-02-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_update_flower_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='femaleflower',
            name='sepals',
        ),
        migrations.RemoveField(
            model_name='hermaphroditeflower',
            name='sepals',
        ),
        migrations.RemoveField(
            model_name='maleflower',
            name='sepals',
        ),
        migrations.AddField(
            model_name='femaleflower',
            name='sepal_arrangement',
            field=models.CharField(choices=[('NONE', 'None / لا يوجد'), ('RANGE', 'Range / نطاق محدد'), ('INDEFINITE', 'Indefinite / غير محدد')], default='RANGE', max_length=20, verbose_name='Sepal Arrangement / نوع السبلات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='femaleflower',
            name='sepal_range_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Maximum Sepals / الحد الأقصى للسبلات'),
        ),
        migrations.AddField(
            model_name='femaleflower',
            name='sepal_range_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Minimum Sepals / الحد الأدنى للسبلات'),
        ),
        migrations.AddField(
            model_name='femaleflower',
            name='sepals_fused',
            field=models.BooleanField(default=False, verbose_name='Fused Sepals (Gamosepalous) / سبلات مندمجة'),
        ),
        migrations.AddField(
            model_name='femaleflower',
            name='sepals_size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sepal Size / حجم السبلات'),
        ),
        migrations.AddField(
            model_name='hermaphroditeflower',
            name='sepal_arrangement',
            field=models.CharField(choices=[('NONE', 'None / لا يوجد'), ('RANGE', 'Range / نطاق محدد'), ('INDEFINITE', 'Indefinite / غير محدد')], default='RANGE', max_length=20, verbose_name='Sepal Arrangement / نوع السبلات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hermaphroditeflower',
            name='sepal_range_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Maximum Sepals / الحد الأقصى للسبلات'),
        ),
        migrations.AddField(
            model_name='hermaphroditeflower',
            name='sepal_range_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Minimum Sepals / الحد الأدنى للسبلات'),
        ),
        migrations.AddField(
            model_name='hermaphroditeflower',
            name='sepals_fused',
            field=models.BooleanField(default=False, verbose_name='Fused Sepals (Gamosepalous) / سبلات مندمجة'),
        ),
        migrations.AddField(
            model_name='hermaphroditeflower',
            name='sepals_size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sepal Size / حجم السبلات'),
        ),
        migrations.AddField(
            model_name='maleflower',
            name='sepal_arrangement',
            field=models.CharField(choices=[('NONE', 'None / لا يوجد'), ('RANGE', 'Range / نطاق محدد'), ('INDEFINITE', 'Indefinite / غير محدد')], default='RANGE', max_length=20, verbose_name='Sepal Arrangement / نوع السبلات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maleflower',
            name='sepal_range_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Maximum Sepals / الحد الأقصى للسبلات'),
        ),
        migrations.AddField(
            model_name='maleflower',
            name='sepal_range_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Minimum Sepals / الحد الأدنى للسبلات'),
        ),
        migrations.AddField(
            model_name='maleflower',
            name='sepals_fused',
            field=models.BooleanField(default=False, verbose_name='Fused Sepals (Gamosepalous) / سبلات مندمجة'),
        ),
        migrations.AddField(
            model_name='maleflower',
            name='sepals_size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sepal Size / حجم السبلات'),
        ),
    ]
