# Generated by Django 5.0.2 on 2025-02-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_femaleflower_sepals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='femaleflower',
            name='sepals_size',
        ),
        migrations.RemoveField(
            model_name='hermaphroditeflower',
            name='sepals_size',
        ),
        migrations.RemoveField(
            model_name='maleflower',
            name='sepals_size',
        ),
        migrations.AlterField(
            model_name='femaleflower',
            name='sepal_arrangement',
            field=models.CharField(choices=[('NONE', 'None / لا يوجد'), ('RANGE', 'Range / نطاق محدد'), ('INDEFINITE', 'Indefinite / غير محدد')], default='RANGE', max_length=20, verbose_name='Sepal Arrangement / نوع السبلات'),
        ),
        migrations.AlterField(
            model_name='femaleflower',
            name='sepals_fused',
            field=models.BooleanField(default=False, verbose_name='Fused Sepals (Gamosepalous) / سبلات ملتحمة'),
        ),
        migrations.AlterField(
            model_name='hermaphroditeflower',
            name='sepal_arrangement',
            field=models.CharField(choices=[('NONE', 'None / لا يوجد'), ('RANGE', 'Range / نطاق محدد'), ('INDEFINITE', 'Indefinite / غير محدد')], default='RANGE', max_length=20, verbose_name='Sepal Arrangement / نوع السبلات'),
        ),
        migrations.AlterField(
            model_name='hermaphroditeflower',
            name='sepals_fused',
            field=models.BooleanField(default=False, verbose_name='Fused Sepals (Gamosepalous) / سبلات ملتحمة'),
        ),
        migrations.AlterField(
            model_name='maleflower',
            name='sepal_arrangement',
            field=models.CharField(choices=[('NONE', 'None / لا يوجد'), ('RANGE', 'Range / نطاق محدد'), ('INDEFINITE', 'Indefinite / غير محدد')], default='RANGE', max_length=20, verbose_name='Sepal Arrangement / نوع السبلات'),
        ),
        migrations.AlterField(
            model_name='maleflower',
            name='sepals_fused',
            field=models.BooleanField(default=False, verbose_name='Fused Sepals (Gamosepalous) / سبلات ملتحمة'),
        ),
    ]
