# Generated by Django 5.0.2 on 2025-02-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_femaleflower_petals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='femaleflower',
            name='stamens',
        ),
        migrations.RemoveField(
            model_name='hermaphroditeflower',
            name='stamens',
        ),
        migrations.RemoveField(
            model_name='maleflower',
            name='carpels',
        ),
        migrations.AlterField(
            model_name='femaleflower',
            name='carpels',
            field=models.CharField(default='Not specified', max_length=255, verbose_name='Carpels / الكرابل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hermaphroditeflower',
            name='carpels',
            field=models.CharField(default='Not specified', max_length=255, verbose_name='Carpels / الكرابل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maleflower',
            name='stamens',
            field=models.CharField(default='Not specified', max_length=255, verbose_name='Stamens / الاسدية'),
            preserve_default=False,
        ),
    ]
