# Generated by Django 5.0.2 on 2025-02-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_femaleflower_stamens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hermaphroditeflower',
            name='stamens',
            field=models.CharField(default='Not specified', max_length=255, verbose_name='Stamens / الاسدية'),
        ),
    ]
