# Generated by Django 5.1.2 on 2025-04-04 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_hermaphroditeflower_stamens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_arabic', models.CharField(max_length=100, verbose_name='Arabic Name / الاسم بالعربي')),
                ('name_english', models.CharField(blank=True, max_length=100, verbose_name='English Name / الاسم بالانجليزي')),
                ('name_scientific', models.CharField(max_length=100, verbose_name='Scientific Name / الاسم العلمي')),
                ('classification', models.CharField(max_length=100, verbose_name='Classification / التصنيف')),
                ('seed_shape_arabic', models.CharField(max_length=100, verbose_name='Seed Shape (Arabic) / شكل البذرة')),
                ('seed_shape_english', models.CharField(blank=True, max_length=100, verbose_name='Seed Shape (English)')),
                ('cotyledon_type', models.CharField(choices=[('MONO', 'Monocotyledon / فلقة واحدة'), ('DI', 'Dicotyledon / فلقتين')], max_length=4, verbose_name='Cotyledon Type / نوع الفلقة')),
                ('flower_type', models.CharField(choices=[('BOTH', 'Both Male and Female / ذكرية وأنثوية'), ('HERMAPHRODITE', 'Hermaphrodite / خنثى')], max_length=20, verbose_name='Flower Type / نوع الزهرة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('additional_details', models.JSONField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.plantfamily', verbose_name='Family / العائلة')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plant Submission',
                'verbose_name_plural': 'Plant Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
