# Generated by Django 5.0.2 on 2025-04-05 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_plantsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description / الوصف'),
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plants/', verbose_name='Image / الصورة')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption / التعليق')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Image / الصورة الرئيسية')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date / تاريخ الرفع')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.plant', verbose_name='Plant / النبات')),
            ],
            options={
                'verbose_name': 'Plant Image',
                'verbose_name_plural': 'Plant Images',
                'ordering': ['-is_primary', '-upload_date'],
            },
        ),
    ]
