# Generated by Django 5.0.2 on 2025-04-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_plant_description_plantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantsubmission',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description / الوصف'),
        ),
    ]
