# Generated by Django 5.0.2 on 2025-04-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_plantsubmission_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/', verbose_name='Plant Image / صورة النبات'),
        ),
        migrations.DeleteModel(
            name='PlantImage',
        ),
    ]
