# Generated by Django 5.0.2 on 2025-04-07 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_plant_image_delete_plantimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude / خط العرض')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude / خط الطول')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity / الكمية')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At / تم إنشاؤه في')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.plant', verbose_name='Plant / النبات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_locations', to=settings.AUTH_USER_MODEL, verbose_name='Submitted by / قدمت من قبل')),
            ],
            options={
                'verbose_name': 'Plant Location',
                'verbose_name_plural': 'Plant Locations',
                'ordering': ['-created_at'],
            },
        ),
    ]
