name: grow
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/login-bg.png
    - assets/images/login-logo.png
    - assets/images/homescreen_banner.png
    - assets/images/homescreen_p1.png
    - assets/images/homescreen_p2.png
    - assets/images/homescreen_p3.png
    - assets/images/homescreen_p4.png
    - assets/images/homescreen_p5.png
    - assets/images/homescreen_p6.png
  fonts:
    - family: Rakkas
      fonts:
        - asset: assets/fonts/Rakkas-Regular.ttf